<a href="https://colab.research.google.com/github/fawziafaraag/first-task/blob/main/Lab_2_Trainees_from_Vector_Space_to_Gram_Shmidt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Linear Combination
### Use NumPy

$$v_1=\begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix},
v_2=\begin{bmatrix} 3 \\ 5 \\ 1 \end{bmatrix},
v_3=\begin{bmatrix} 0 \\ 0 \\ 8 \end{bmatrix}$$
- Find <b>b</b> vector where $$b=3v_1+0v_2+0v_3$$
- Find <b>x</b> vector where $$x=-v_1+v_2-0.5v_3$$

In [ ]:
import numpy as np

In [ ]:
v1= np.array([[1],[2],[3]])
v2= np.array([[3],[5],[1]])
v3= np.array([[0],[0],[8]])
b=np.multiply(v1,3)+np.multiply(v2,0)+np.multiply(v3,0)
print('b:\n',b)
x=np.multiply(v1,-1)+np.multiply(v2,1)+np.multiply(v3,-.5)
print('x:\n',x)

b:
 [[3]
 [6]
 [9]]
x:
 [[ 2.]
 [ 3.]
 [-6.]]


b:
[[3]
 [6]
 [9]]

x:
[[ 2.]
 [ 3.]
 [-6.]]


## Vector Span
### Use Numpy (matrix inverse) and SymPy (rref)

#### Is $$v=\begin{bmatrix} 19 \\ 10 \\ -1 \end{bmatrix}$$ in the span of 
$$v_1=\begin{bmatrix} 3 \\ -1 \\ 2 \end{bmatrix},
v_2=\begin{bmatrix} -5 \\ 0 \\ 1 \end{bmatrix},
v_3=\begin{bmatrix} 1 \\ 7 \\ -4 \end{bmatrix}$$

In [ ]:
import numpy as np
import sympy as sm

In [ ]:
v=np.array([[3,-5,1,19],
            [-1,0,7,10],
            [2,1,-4,-1]])
m=sm.Matrix(v)
a=m.rref()
a

(Matrix([
 [1, 0, 0,  4],
 [0, 1, 0, -1],
 [0, 0, 1,  2]]), (0, 1, 2))

(Matrix([
 [1, 0, 0,  4],
 [0, 1, 0, -1],
 [0, 0, 1,  2]]),
 (0, 1, 2))

In [ ]:
v1= np.array([[3],[-1],[2]])
v2= np.array([[-5],[0],[1]])
v3= np.array([[1],[7],[-4]])
b=np.multiply(v1,4)+np.multiply(v2,-1)+np.multiply(v3,2)
print(b)

[[19]
 [10]
 [-1]]


[[ 4.]
 [-1.]
 [ 2.]]


## Vector Linear Independence
### Use rref and determinant
- Consider the following sets of vectors in R3. If the set is independent, prove it. 
- If the set is dependent, find a nontrivial linear combination of the vectors which is equal to 0.
    - {(2, 0, -3), (1, 1, 1), (1, 7, 2)}.
    - {(1, 2, -1), (4, 1, 3), (-10, 1, -11)}.

<b>Hint: we have to determine whether this implies that 𝒂=𝒃=𝒄=𝟎.</b>

In [ ]:
m=sm.Matrix([[2,1,1],
             [0,1,7],
             [-3,1,2]])
m.rref()

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]), (0, 1, 2))

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]),
 (0, 1, 2))

In [ ]:
M = sm.Matrix([[1,4,-10],
               [2,1,1],
               [-1,3,-11]])
M.rref()

(Matrix([
 [1, 0,  2],
 [0, 1, -3],
 [0, 0,  0]]), (0, 1))

(Matrix([
 [1, 0,  2],
 [0, 1, -3],
 [0, 0,  0]]),
 (0, 1))

0

## Linear Transformation
### Ex.1

$$T=\begin{bmatrix} 1&2 \\ 3&7 \end{bmatrix}$$
- Write the linear transformation expression of this matrix. i.e. Linear functions of x,y. 
- Apply the transformation matrix <b>T</b> to the following vectors:
$$\begin{bmatrix} 1 \\ 0 \end{bmatrix},\begin{bmatrix} 0 \\ 1 \end{bmatrix} $$
- Find all points <b>(x,y)</b> such that <b>T(x,y)=(1,0)</b>

In [ ]:
m=np.array([[1,2],
            [3,7]])
M = sm.Matrix(m)
print(M.rref())
v1=M[:,0]
v2=M[:,1]
print('\na.v1=\n',v1,'\na.v2=\n',v2)


(Matrix([
[1, 0],
[0, 1]]), (0, 1))

a.v1=
 Matrix([[1], [3]]) 
a.v2=
 Matrix([[2], [7]])


A.v1=
[[1]
 [3]]

A.v2=
[[2]
 [7]]


In [ ]:
M = np.array([[1,2],
               [3,7]])
np.linalg.det(M)

0.9999999999999991

In [ ]:
m=np.linalg.inv(M)
m

array([[ 7., -2.],
       [-3.,  1.]])

In [ ]:
print("(x,y):\n",m[:,0])

(x,y):
 [ 7. -3.]


(x,y):
[[ 7.]
 [-3.]]


### Ex.2
### For the expression $$T\begin{bmatrix} x \\ y \end{bmatrix}=\begin{bmatrix} x+y \\ y \end{bmatrix}$$
- Find the transformation matrix.
- Represent the transformation graphically <b>(on paper)</b>.
- Find all points <b>(x,y)</b> such that <b>T(x,y)=(3,4)</b>

x:
[[-1.]
 [ 4.]]


## Determinant
### Find Determinant of:

$$\begin{bmatrix} 3&8 \\ 4&6 \end{bmatrix} , \begin{bmatrix} 4&6 \\ 3&8 \end{bmatrix}$$
$$\begin{bmatrix} 6&1&1 \\ 4&-2&5 \\ 2&8&7\end{bmatrix}$$
$$\begin{bmatrix} 3&2&0&1 \\ 4&0&1&2 \\ 3&0&2&1 \\ 9&2&3&1\end{bmatrix}$$


In [ ]:
m1=np.array([[3,8],
             [4,6]])
m2=np.array([[4,6],
             [3,8]])
m3=np.array([[6,1,1],
            [4,-2,5],
             [2,8,7]])
m4=np.array([[3,2,0,1],
             [4,0,1,2],
             [3,0,2,1],
             [9,2,3,1]])
d1=np.linalg.det(m1)
d2=np.linalg.det(m2)
d3=np.linalg.det(m3)
d4=np.linalg.det(m4)
print('1.',d1,'\n2.',d2,'\n3.',d3,'\n4.',d4)



1. -14.000000000000004 
2. 14.000000000000004 
3. -306.0 
4. 24.000000000000004


1.  -14.000000000000004
2.  14.000000000000004
3.  -306.0
4.  24.000000000000004


## Matrix Rank
### Find the rank of the matrix (use rref and confirm using matrix_rank())

$$X = \begin{bmatrix} 1&2&4&4 \\ 3&4&8&0 \end{bmatrix}$$
$$Y = \begin{bmatrix} 1&2&3 \\ 2&3&5 \\ 3&4&7 \\ 4&5&9  \end{bmatrix}$$

In [ ]:
x=np.array([[1,2,4,4],
            [3,4,8,0]])
X=sm.Matrix(x)
rank1=np.linalg.matrix_rank(x)
print(X.rref(),'\nx rank: ',rank1)

(Matrix([
[1, 0, 0, -8],
[0, 1, 2,  6]]), (0, 1)) 
x rank:  2


(Matrix([
[1, 0, 0, -8],
[0, 1, 2,  6]]), (0, 1))

X rank: 2


In [ ]:
y=np.array([[1,2,3],
            [2,3,5],
            [3,4,7],
            [4,5,9]])
Y=sm.Matrix(y)
rank1=np.linalg.matrix_rank(y)
print(Y.rref(),'\nY rank: ',rank1)

(Matrix([
[1, 0, 1],
[0, 1, 1],
[0, 0, 0],
[0, 0, 0]]), (0, 1)) 
Y rank:  2


(Matrix([
[1, 0, 1],
[0, 1, 1],
[0, 0, 0],
[0, 0, 0]]), (0, 1))

Y rank: 2


## Matrix Inverse
### Find the inverse:

$$\begin{bmatrix} 3&8 \\ 4&6 \end{bmatrix} , \begin{bmatrix} 4&6 \\ 3&8 \end{bmatrix}$$
$$\begin{bmatrix} 6&1&1 \\ 4&-2&5 \\ 2&8&7\end{bmatrix}$$
$$\begin{bmatrix} 3&2&0&1 \\ 4&0&1&2 \\ 3&0&2&1 \\ 9&2&3&1\end{bmatrix}$$

In [ ]:
m1=np.array([[3,8],
             [4,6]])
m2=np.array([[4,6],
             [3,8]])
m3=np.array([[6,1,1],
            [4,-2,5],
             [2,8,7]])
m4=np.array([[3,2,0,1],
             [4,0,1,2],
             [3,0,2,1],
             [9,2,3,1]])
inv1=np.linalg.inv(m1)
inv2=np.linalg.inv(m2)
inv3=np.linalg.inv(m3)
inv4=np.linalg.inv(m4)
print('1.\n',inv1,'\n2.\n',inv2,'\n3.\n',inv3,'\n4.\n',inv4)

1.
 [[-0.42857143  0.57142857]
 [ 0.28571429 -0.21428571]] 
2.
 [[ 0.57142857 -0.42857143]
 [-0.21428571  0.28571429]] 
3.
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]] 
4.
 [[-0.25        0.25       -0.5         0.25      ]
 [ 0.66666667 -0.5         0.5        -0.16666667]
 [ 0.16666667 -0.5         1.         -0.16666667]
 [ 0.41666667  0.25        0.5        -0.41666667]]


1.
 [[-0.42857143  0.57142857]
 [ 0.28571429 -0.21428571]]

2.
 [[ 0.57142857 -0.42857143]
 [-0.21428571  0.28571429]]

3.
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]

4.
 [[-0.25        0.25       -0.5         0.25      ]
 [ 0.66666667 -0.5         0.5        -0.16666667]
 [ 0.16666667 -0.5         1.         -0.16666667]
 [ 0.41666667  0.25        0.5        -0.41666667]]


## Changing Basis (Orthogonal Coordinates)
### Perform the following (Once by dot product and another by matix). 
### First confirm b1 and b2 are orthogonal basis.
![image-3.png](attachment:image-3.png)

Using dot product
vb:
[[2.]
 [3.]]


Using transformation matrix
vb:
[[2.]
 [3.]]


## Changing Basis (Non-Orthogonal Coordinates)
### Perform the following. 
### First confirm b1 and b2 are non-orthogonal basis.
![image-4.png](attachment:image-4.png)

vb:
[[1.5]
 [0.5]]


## Transformation in Non-Orthonormal Space
![image-3.png](attachment:image-3.png)

TB1 =
 [[ 2.  1.]
 [-3. -2.]]

TB2 =
 [[ 2.  1.]
 [-5. -2.]]

vb_TB1 =
 [[ 3.5]
 [-5.5]]

vb_TB2 =
 [[ 3.5]
 [-8.5]]


## Gram–Schmidt Process (Orthogonalization)
![image-2.png](attachment:image-2.png)
#### Confirm your answer using numpy.linalg.qr() function
#### Make sure all vectors given above are basis in R3 space.
#### Confirm that the orthogonal matrix has orthonormal vectors.
#### Confirm that the transpose of the orthogonal matrix is it's inverse.
#### Reflect the vector r = (1,3,4) arround the xy plane.
#### Round all results to 3 decimal points.

det(V): -15.0
Mrref:
 (Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]]), (0, 1, 2))


u1:
[[1]
 [2]
 [0]]

u2:
[[ 6.]
 [-3.]
 [-6.]]

u3:
[[ 0.44444444]
 [-0.22222222]
 [ 0.55555556]]

e1:
[[0.4472136 ]
 [0.89442719]
 [0.        ]]

e2:
[[ 0.66666667]
 [-0.33333333]
 [-0.66666667]]

e3:
[[ 0.59628479]
 [-0.2981424 ]
 [ 0.74535599]]


Using QR:
[[-0.4472136   0.66666667  0.59628479]
 [-0.89442719 -0.33333333 -0.2981424 ]
 [-0.         -0.66666667  0.74535599]]


1.0

Q Inverse:
 [[-0.447 -0.894 -0.   ]
 [ 0.667 -0.333 -0.667]
 [ 0.596 -0.298  0.745]]
Q Transpose
 [[-0.447 -0.894 -0.   ]
 [ 0.667 -0.333 -0.667]
 [ 0.596 -0.298  0.745]]


Transformation matrix in the non-orthonormal basis:
[[ 0.28888889  0.35555556 -0.88888889]
 [ 0.35555556  0.82222222  0.44444444]
 [-0.88888889  0.44444444 -0.11111111]]

Transformed vector:
[[-2.2]
 [ 4.6]
 [ 0. ]]
